### ISSUE TITLE
Unify return value

### ISSUE THREAD

**Issue by philsch** [sendwithus/sendwithus_php#35]
Hi there,

The result value differs a lot depending on the request and if it was successful or not.
For example:
* Request returning one item results in a PHP object
* Request returning multiple items results in a PHP array
* Requesting non existing template raises HTTP 400 and results in a PHP object with 'code','status'...

It would be really useful to have a unified result type.
Maybe something like:
```
array(
    'status' => 'success' | 'error'
    'code' => HTTP status code
    'data' => array(...)
)
```

Maybe it's possible to find a solution that can be merged into your repository. Do you have any suggestions?

Thanks!

**Comment by demoore** [comment]
Hey @philsch I feel your pain — I often debug PHP client problems. Our API makes this a little difficult to do. Wait until our next version, I promise it will be saner.
