### ISSUE TITLE
Get a List all Logs

### ISSUE THREAD

**Issue by wikimatze** [sendwithus/sendwithus_php#43]
Hi there,

I'm playing around with the [API log](https://www.sendwithus.com/docs/api#logs) and it working great with the `count` and `offset` param. What about the other mentioned on the documentation: 

- `created_gt`: Return logs created strictly after the given UTC timestamp.
- `created_gte`: Return logs created on or after the given UTC timestamp.
- `created_lt`: Return logs created strictly before the given UTC timestamp.
- `created_lte`: Return logs created on or before the given UTC timestamp.

Is it possible to add these as optional parameters in the [logs method](https://github.com/sendwithus/sendwithus_php/blob/master/lib/API.php#L441) method and define them as default with null.

Bests regards from Berlin,

Matthias

**Comment by moxuz** [comment]
Hey Matthias,
We will get this added by the end of next week! This endpoint isn't the most performant and might not be the best solution for what you're trying to do. Hit up support@sendwithus.com and we can talk about it :)

**Comment by moxuz** [comment]
I have added the functionality!
