### ISSUE TITLE
Custom log handler for debug

### ISSUE THREAD

**Issue by bogdanhadadeasv** [sendwithus/sendwithus_php#74]
### Client version
v6.0.0

### Expected behaviour
I'd like to be able to use a custom handler for the debug messages. Since it would be tricky to change the functionality of error_log, the best way I can think of doing this would be to pass a function to the API.php constructor which will be used for error logging, defaulting to error_log.

```
    protected $ERROR_HANDLER = null;

    public function __construct($api_key, $options = array(), $error_handler = null) {
        $this->API_KEY = $api_key;
        $this->API_CLIENT_STUB = sprintf($this->API_CLIENT_STUB,
            $this->API_CLIENT_VERSION);
        $this->ERROR_HANDLER = $error_handler;

        foreach ($options as $key => $value) {
            $this->$key = $value;
        }
    }


    private function log_message($message)
    {
        if ($this->ERROR_HANDLER) {
            call_user_func($this->ERROR_HANDLER, $message);
        } else {
            error_log($message);
        }
    }
```

And then when making a new instance:

```
new EmailSystem(
                \Config::get('sendWithUs.api_key'),
                \Config::get('sendWithUs.options'),
                function ($message) {
                    \Log::debug('[SendWithUs][Debug] ' . $message);
                }
```
This also implies changing everywhere we use error_log to the new log_message method. 

### Actual behaviour
It uses the default 'error_log' method for logging. No way of changing it.

**Comment by dylan-swu** [comment]
Cool idea! I like it 😄 @bogdanhadadeasv think you can put together a PR? I'd be happy to review.
