### ISSUE TITLE
Why no Packagist listing?

### ISSUE THREAD

**Issue by Crell** [sendwithus/sendwithus_php#87]
Why is this project not listed on Packagist?  It has ample stable releases, but GitHub's throttling is making it difficult to download directly.  Why not list it on Packagist to make it easier to install?

**Comment by Crell** [comment]
Ah ha, much nicer, thanks.  Though it appears there is no license info available to Packagist, which is also problematic.  (It needs to be listed in the composer.json file.  There's a key for it.)

**Comment by demoore** [comment]
On it: https://github.com/sendwithus/sendwithus_php/pull/88

Thanks @Crell  :smile:
